#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bndl-lamp-basic
Version  : 1.4
Release  : 17
URL      : http://localhost/cgit/projects/bndl-lamp-basic/snapshot/bndl-lamp-basic-1.4.tar.gz
Source0  : http://localhost/cgit/projects/bndl-lamp-basic/snapshot/bndl-lamp-basic-1.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: bndl-lamp-basic-autostart = %{version}-%{release}
Requires: bndl-lamp-basic-license = %{version}-%{release}
Requires: bndl-lamp-basic-services = %{version}-%{release}

%description
No detailed description available

%package autostart
Summary: autostart components for the bndl-lamp-basic package.
Group: Default

%description autostart
autostart components for the bndl-lamp-basic package.


%package license
Summary: license components for the bndl-lamp-basic package.
Group: Default

%description license
license components for the bndl-lamp-basic package.


%package services
Summary: services components for the bndl-lamp-basic package.
Group: Systemd services

%description services
services components for the bndl-lamp-basic package.


%prep
%setup -q -n bndl-lamp-basic-1.4
cd %{_builddir}/bndl-lamp-basic-1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604083981
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604083981
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bndl-lamp-basic
cp %{_builddir}/bndl-lamp-basic-1.4/LICENSE %{buildroot}/usr/share/package-licenses/bndl-lamp-basic/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/php-fpm.service

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/httpd.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bndl-lamp-basic/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/httpd.service
